version: '3'
services:
  api:
    container_name: api-express
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
        - database
  database:
    image: mongo:latest
    container_name: db-mongo
    expose:
      - 27017
    ports:
      - 27017:27017